package com.hexiaofei.provider0.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hexiaofei.provider0.domain.LszTag;
import com.hexiaofei.provider0.domain.LszTagExample.Criteria;
import com.hexiaofei.provider0.domain.LszTagExample.Criterion;
import com.hexiaofei.provider0.domain.LszTagExample;
import java.util.List;
import java.util.Map;

public class LszTagSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String countByExample(LszTagExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("lsz_tag");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String deleteByExample(LszTagExample example) {
        BEGIN();
        DELETE_FROM("lsz_tag");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String insertSelective(LszTag record) {
        BEGIN();
        INSERT_INTO("lsz_tag");
        
        if (record.getTagId() != null) {
            VALUES("tagId", "#{tagId,jdbcType=INTEGER}");
        }
        
        if (record.getRecordId() != null) {
            VALUES("recordId", "#{recordId,jdbcType=INTEGER}");
        }
        
        if (record.getTagType() != null) {
            VALUES("tagType", "#{tagType,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaCode() != null) {
            VALUES("wordMetaCode", "#{wordMetaCode,jdbcType=INTEGER}");
        }
        
        if (record.getWordMetaEn() != null) {
            VALUES("wordMetaEn", "#{wordMetaEn,jdbcType=CHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            VALUES("wordMetaZh", "#{wordMetaZh,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String selectByExample(LszTagExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("tagId");
        } else {
            SELECT("tagId");
        }
        SELECT("recordId");
        SELECT("tagType");
        SELECT("wordMetaCode");
        SELECT("wordMetaEn");
        SELECT("wordMetaZh");
        FROM("lsz_tag");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        LszTag record = (LszTag) parameter.get("record");
        LszTagExample example = (LszTagExample) parameter.get("example");
        
        BEGIN();
        UPDATE("lsz_tag");
        
        if (record.getTagId() != null) {
            SET("tagId = #{record.tagId,jdbcType=INTEGER}");
        }
        
        if (record.getRecordId() != null) {
            SET("recordId = #{record.recordId,jdbcType=INTEGER}");
        }
        
        if (record.getTagType() != null) {
            SET("tagType = #{record.tagType,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaCode() != null) {
            SET("wordMetaCode = #{record.wordMetaCode,jdbcType=INTEGER}");
        }
        
        if (record.getWordMetaEn() != null) {
            SET("wordMetaEn = #{record.wordMetaEn,jdbcType=CHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            SET("wordMetaZh = #{record.wordMetaZh,jdbcType=CHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("lsz_tag");
        
        SET("tagId = #{record.tagId,jdbcType=INTEGER}");
        SET("recordId = #{record.recordId,jdbcType=INTEGER}");
        SET("tagType = #{record.tagType,jdbcType=VARCHAR}");
        SET("wordMetaCode = #{record.wordMetaCode,jdbcType=INTEGER}");
        SET("wordMetaEn = #{record.wordMetaEn,jdbcType=CHAR}");
        SET("wordMetaZh = #{record.wordMetaZh,jdbcType=CHAR}");
        
        LszTagExample example = (LszTagExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    public String updateByPrimaryKeySelective(LszTag record) {
        BEGIN();
        UPDATE("lsz_tag");
        
        if (record.getRecordId() != null) {
            SET("recordId = #{recordId,jdbcType=INTEGER}");
        }
        
        if (record.getTagType() != null) {
            SET("tagType = #{tagType,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaCode() != null) {
            SET("wordMetaCode = #{wordMetaCode,jdbcType=INTEGER}");
        }
        
        if (record.getWordMetaEn() != null) {
            SET("wordMetaEn = #{wordMetaEn,jdbcType=CHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            SET("wordMetaZh = #{wordMetaZh,jdbcType=CHAR}");
        }
        
        WHERE("tagId = #{tagId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsz_tag
     *
     * @mbggenerated Sat Nov 28 15:02:24 CST 2020
     */
    protected void applyWhere(LszTagExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}