server:
  port: 80
  connection-timeout: 5000                              # 连接超时
  session:                                              # session会话超时单位S(秒)，
    timeout: 3600                                       # springboot2.x server.servlet.session.timeout:PT2H(duration类)
  tomcat:
    uri-encoding: utf-8
    max-threads: 100                                    # 最大线程数
    accesslog:
      enabled: true                                     # 开启日志
      directory: /Users/hexiaofei/Desktop/logs/lsz-client/tomcat   # 日志目录
      buffered: true                                    # 缓冲输出，使其只定期刷新。
      rotate: true                                      # Enable access log rotation.指定是否启用日志轮转。默认为true。这个参数决定是否需要切换切换日志文件，如果被设置为false，则日志文件不会切换，即所有文件打到同一个日志文件中，并且file-date-format参数也会被忽略
      file-date-format: .yyyy-MM-dd                     # 要放在日志文件名中的日期格式。rotate为false的时候，这个也就不生效了。
      pattern: common                                   # 定义access日志的格式,可以自定义，也可以用Access log内置了两个日志格式模板，
      rename-on-rotate: false                           # Defer inclusion of the date stamp in the file name until rotate time.
      request-attributes-enabled: false                 # Set request attributes for IP address, Hostname, protocol and port used for the request.
      prefix: access_log                                # Log file name prefix.
      suffix: .log                                      # Log file name suffix.
spring:
  datasource:
    username: 'lishizhou'
    password: '000000'
    url: jdbc:mysql://lishizhou-mysql:3306/lishizhou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 2                                  # 初始化建立的连接数
      minIdle: 2                                      # 最小的限制连接数
      maxActive: 10                                   # 最大的连接数
      maxWait: 6000                                   # 从连接池获取连接超时
      timeBetweenEvictionRunsMillis: 6000             # 配置间隔多久启动一次DestroyThread，对连接池内的连接才进行一次检测，单位是毫秒。
      minEvictableIdleTimeMillis: 30000               # 闲置连接大于次值时将被驱逐
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true                             # 设置从连接池获取连接时是否检查连接有效性，为true时，如果连接空闲时间超过minEvictableIdleTimeMillis进行检查，否则不检查，为false时，不检查
      testOnBorrow: false                             # 设置从连接池获取连接时是否检查连接有效性，true时，每次都检查;false时，不检查
      testOnReturn: false                             # 设置往连接池归还连接时是否检查连接有效性，true时，每次都检查;false时，不检查
      poolPreparedStatements: false                   # 打开PSCache，并且指定每个连接上PSCache的大小，Oracle等支持游标的数据库，打开此开关，会以数量级提升性能，具体查阅PSCache相关资料。MySQL建议关闭。
  freemarker:
    enabled: false
  thymeleaf:
    mode: HTML5
    prefix: classpath:/lsz_client/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    cache: false

endpoints:
  shutdown:
    enabled: true                            # 启用shutdown
    sensitive: false                         # 禁用密码验证

platform:
  id: lishizhou
  name: 历史轴
  serverId: lishizhou
  serverName: 历史轴
  serverUrl: localhost