package com.lcyj.sms.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.lcyj.sms.model.SmsEmail;
import com.lcyj.sms.model.SmsEmailExample.Criteria;
import com.lcyj.sms.model.SmsEmailExample.Criterion;
import com.lcyj.sms.model.SmsEmailExample;
import java.util.List;
import java.util.Map;

public class SmsEmailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String countByExample(SmsEmailExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sms_email");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String deleteByExample(SmsEmailExample example) {
        BEGIN();
        DELETE_FROM("sms_email");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String insertSelective(SmsEmail record) {
        BEGIN();
        INSERT_INTO("sms_email");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSmsUserId() != null) {
            VALUES("smsUserId", "#{smsUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getToEmail() != null) {
            VALUES("toEmail", "#{toEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformId() != null) {
            VALUES("platformId", "#{platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            VALUES("serverId", "#{serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getFromEmail() != null) {
            VALUES("fromEmail", "#{fromEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailType() != null) {
            VALUES("emailType", "#{emailType,jdbcType=VARCHAR}");
        }
        
        if (record.getSubject() != null) {
            VALUES("subject", "#{subject,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getEnclosure() != null) {
            VALUES("enclosure", "#{enclosure,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            VALUES("sendStatus", "#{sendStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendTime() != null) {
            VALUES("sendTime", "#{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendCount() != null) {
            VALUES("sendCount", "#{sendCount,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateTime() != null) {
            VALUES("lastUpdateTime", "#{lastUpdateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String selectByExample(SmsEmailExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("smsUserId");
        SELECT("toEmail");
        SELECT("platformId");
        SELECT("serverId");
        SELECT("fromEmail");
        SELECT("emailType");
        SELECT("subject");
        SELECT("content");
        SELECT("enclosure");
        SELECT("sendStatus");
        SELECT("createTime");
        SELECT("sendTime");
        SELECT("sendCount");
        SELECT("lastUpdateTime");
        FROM("sms_email");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SmsEmail record = (SmsEmail) parameter.get("record");
        SmsEmailExample example = (SmsEmailExample) parameter.get("example");
        
        BEGIN();
        UPDATE("sms_email");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getSmsUserId() != null) {
            SET("smsUserId = #{record.smsUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getToEmail() != null) {
            SET("toEmail = #{record.toEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformId() != null) {
            SET("platformId = #{record.platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            SET("serverId = #{record.serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getFromEmail() != null) {
            SET("fromEmail = #{record.fromEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailType() != null) {
            SET("emailType = #{record.emailType,jdbcType=VARCHAR}");
        }
        
        if (record.getSubject() != null) {
            SET("subject = #{record.subject,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getEnclosure() != null) {
            SET("enclosure = #{record.enclosure,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            SET("sendStatus = #{record.sendStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendTime() != null) {
            SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendCount() != null) {
            SET("sendCount = #{record.sendCount,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateTime() != null) {
            SET("lastUpdateTime = #{record.lastUpdateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sms_email");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("smsUserId = #{record.smsUserId,jdbcType=VARCHAR}");
        SET("toEmail = #{record.toEmail,jdbcType=VARCHAR}");
        SET("platformId = #{record.platformId,jdbcType=VARCHAR}");
        SET("serverId = #{record.serverId,jdbcType=VARCHAR}");
        SET("fromEmail = #{record.fromEmail,jdbcType=VARCHAR}");
        SET("emailType = #{record.emailType,jdbcType=VARCHAR}");
        SET("subject = #{record.subject,jdbcType=VARCHAR}");
        SET("content = #{record.content,jdbcType=VARCHAR}");
        SET("enclosure = #{record.enclosure,jdbcType=VARCHAR}");
        SET("sendStatus = #{record.sendStatus,jdbcType=SMALLINT}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        SET("sendCount = #{record.sendCount,jdbcType=INTEGER}");
        SET("lastUpdateTime = #{record.lastUpdateTime,jdbcType=TIMESTAMP}");
        
        SmsEmailExample example = (SmsEmailExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    public String updateByPrimaryKeySelective(SmsEmail record) {
        BEGIN();
        UPDATE("sms_email");
        
        if (record.getSmsUserId() != null) {
            SET("smsUserId = #{smsUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getToEmail() != null) {
            SET("toEmail = #{toEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformId() != null) {
            SET("platformId = #{platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            SET("serverId = #{serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getFromEmail() != null) {
            SET("fromEmail = #{fromEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailType() != null) {
            SET("emailType = #{emailType,jdbcType=VARCHAR}");
        }
        
        if (record.getSubject() != null) {
            SET("subject = #{subject,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getEnclosure() != null) {
            SET("enclosure = #{enclosure,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            SET("sendStatus = #{sendStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendTime() != null) {
            SET("sendTime = #{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendCount() != null) {
            SET("sendCount = #{sendCount,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateTime() != null) {
            SET("lastUpdateTime = #{lastUpdateTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_email
     *
     * @mbggenerated Sat Feb 29 11:20:40 CST 2020
     */
    protected void applyWhere(SmsEmailExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}