package com.lcyj.sms.dao.mapper;

import com.lcyj.sms.model.SmsPlatformServerEmail;
import com.lcyj.sms.model.SmsPlatformServerEmailExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SmsPlatformServerEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsPlatformServerEmailSqlProvider.class, method="countByExample")
    int countByExample(SmsPlatformServerEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @DeleteProvider(type=SmsPlatformServerEmailSqlProvider.class, method="deleteByExample")
    int deleteByExample(SmsPlatformServerEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Delete({
        "delete from sms_platform_server_email",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Insert({
        "insert into sms_platform_server_email (id, platformId, ",
        "serverId, platformName, ",
        "emailAddress, emailPassword, ",
        "emailServerConfigId, businessType, ",
        "businessName)",
        "values (#{id,jdbcType=INTEGER}, #{platformId,jdbcType=VARCHAR}, ",
        "#{serverId,jdbcType=VARCHAR}, #{platformName,jdbcType=VARCHAR}, ",
        "#{emailAddress,jdbcType=VARCHAR}, #{emailPassword,jdbcType=VARCHAR}, ",
        "#{emailServerConfigId,jdbcType=VARCHAR}, #{businessType,jdbcType=VARCHAR}, ",
        "#{businessName,jdbcType=VARCHAR})"
    })
    int insert(SmsPlatformServerEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @InsertProvider(type=SmsPlatformServerEmailSqlProvider.class, method="insertSelective")
    int insertSelective(SmsPlatformServerEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsPlatformServerEmailSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="platformId", property="platformId", jdbcType=JdbcType.VARCHAR),
        @Result(column="serverId", property="serverId", jdbcType=JdbcType.VARCHAR),
        @Result(column="platformName", property="platformName", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailAddress", property="emailAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailPassword", property="emailPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailServerConfigId", property="emailServerConfigId", jdbcType=JdbcType.VARCHAR),
        @Result(column="businessType", property="businessType", jdbcType=JdbcType.VARCHAR),
        @Result(column="businessName", property="businessName", jdbcType=JdbcType.VARCHAR)
    })
    List<SmsPlatformServerEmail> selectByExample(SmsPlatformServerEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Select({
        "select",
        "id, platformId, serverId, platformName, emailAddress, emailPassword, emailServerConfigId, ",
        "businessType, businessName",
        "from sms_platform_server_email",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="platformId", property="platformId", jdbcType=JdbcType.VARCHAR),
        @Result(column="serverId", property="serverId", jdbcType=JdbcType.VARCHAR),
        @Result(column="platformName", property="platformName", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailAddress", property="emailAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailPassword", property="emailPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailServerConfigId", property="emailServerConfigId", jdbcType=JdbcType.VARCHAR),
        @Result(column="businessType", property="businessType", jdbcType=JdbcType.VARCHAR),
        @Result(column="businessName", property="businessName", jdbcType=JdbcType.VARCHAR)
    })
    SmsPlatformServerEmail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsPlatformServerEmailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SmsPlatformServerEmail record, @Param("example") SmsPlatformServerEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsPlatformServerEmailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SmsPlatformServerEmail record, @Param("example") SmsPlatformServerEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsPlatformServerEmailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SmsPlatformServerEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Update({
        "update sms_platform_server_email",
        "set platformId = #{platformId,jdbcType=VARCHAR},",
          "serverId = #{serverId,jdbcType=VARCHAR},",
          "platformName = #{platformName,jdbcType=VARCHAR},",
          "emailAddress = #{emailAddress,jdbcType=VARCHAR},",
          "emailPassword = #{emailPassword,jdbcType=VARCHAR},",
          "emailServerConfigId = #{emailServerConfigId,jdbcType=VARCHAR},",
          "businessType = #{businessType,jdbcType=VARCHAR},",
          "businessName = #{businessName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SmsPlatformServerEmail record);
}