package com.lcyj.sms.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.lcyj.sms.model.SmsPlatformServerEmail;
import com.lcyj.sms.model.SmsPlatformServerEmailExample.Criteria;
import com.lcyj.sms.model.SmsPlatformServerEmailExample.Criterion;
import com.lcyj.sms.model.SmsPlatformServerEmailExample;
import java.util.List;
import java.util.Map;

public class SmsPlatformServerEmailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String countByExample(SmsPlatformServerEmailExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sms_platform_server_email");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String deleteByExample(SmsPlatformServerEmailExample example) {
        BEGIN();
        DELETE_FROM("sms_platform_server_email");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String insertSelective(SmsPlatformServerEmail record) {
        BEGIN();
        INSERT_INTO("sms_platform_server_email");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getPlatformId() != null) {
            VALUES("platformId", "#{platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            VALUES("serverId", "#{serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformName() != null) {
            VALUES("platformName", "#{platformName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailAddress() != null) {
            VALUES("emailAddress", "#{emailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailPassword() != null) {
            VALUES("emailPassword", "#{emailPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailServerConfigId() != null) {
            VALUES("emailServerConfigId", "#{emailServerConfigId,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessType() != null) {
            VALUES("businessType", "#{businessType,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessName() != null) {
            VALUES("businessName", "#{businessName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String selectByExample(SmsPlatformServerEmailExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("platformId");
        SELECT("serverId");
        SELECT("platformName");
        SELECT("emailAddress");
        SELECT("emailPassword");
        SELECT("emailServerConfigId");
        SELECT("businessType");
        SELECT("businessName");
        FROM("sms_platform_server_email");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SmsPlatformServerEmail record = (SmsPlatformServerEmail) parameter.get("record");
        SmsPlatformServerEmailExample example = (SmsPlatformServerEmailExample) parameter.get("example");
        
        BEGIN();
        UPDATE("sms_platform_server_email");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getPlatformId() != null) {
            SET("platformId = #{record.platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            SET("serverId = #{record.serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformName() != null) {
            SET("platformName = #{record.platformName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailAddress() != null) {
            SET("emailAddress = #{record.emailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailPassword() != null) {
            SET("emailPassword = #{record.emailPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailServerConfigId() != null) {
            SET("emailServerConfigId = #{record.emailServerConfigId,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessType() != null) {
            SET("businessType = #{record.businessType,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessName() != null) {
            SET("businessName = #{record.businessName,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sms_platform_server_email");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("platformId = #{record.platformId,jdbcType=VARCHAR}");
        SET("serverId = #{record.serverId,jdbcType=VARCHAR}");
        SET("platformName = #{record.platformName,jdbcType=VARCHAR}");
        SET("emailAddress = #{record.emailAddress,jdbcType=VARCHAR}");
        SET("emailPassword = #{record.emailPassword,jdbcType=VARCHAR}");
        SET("emailServerConfigId = #{record.emailServerConfigId,jdbcType=VARCHAR}");
        SET("businessType = #{record.businessType,jdbcType=VARCHAR}");
        SET("businessName = #{record.businessName,jdbcType=VARCHAR}");
        
        SmsPlatformServerEmailExample example = (SmsPlatformServerEmailExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    public String updateByPrimaryKeySelective(SmsPlatformServerEmail record) {
        BEGIN();
        UPDATE("sms_platform_server_email");
        
        if (record.getPlatformId() != null) {
            SET("platformId = #{platformId,jdbcType=VARCHAR}");
        }
        
        if (record.getServerId() != null) {
            SET("serverId = #{serverId,jdbcType=VARCHAR}");
        }
        
        if (record.getPlatformName() != null) {
            SET("platformName = #{platformName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailAddress() != null) {
            SET("emailAddress = #{emailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailPassword() != null) {
            SET("emailPassword = #{emailPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailServerConfigId() != null) {
            SET("emailServerConfigId = #{emailServerConfigId,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessType() != null) {
            SET("businessType = #{businessType,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinessName() != null) {
            SET("businessName = #{businessName,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_platform_server_email
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    protected void applyWhere(SmsPlatformServerEmailExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}