package com.lcyj.sms.dao.mapper;

import com.lcyj.sms.model.SmsUserinfo;
import com.lcyj.sms.model.SmsUserinfoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SmsUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsUserinfoSqlProvider.class, method="countByExample")
    int countByExample(SmsUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @DeleteProvider(type=SmsUserinfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(SmsUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Delete({
        "delete from sms_userinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Insert({
        "insert into sms_userinfo (id, smsUserId, ",
        "userId, userName, ",
        "idCard, userLevel, ",
        "email, mobileNo, ",
        "emailStatus, mobileNoStatus, ",
        "createTime, platformId)",
        "values (#{id,jdbcType=INTEGER}, #{smsUserId,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{idCard,jdbcType=VARCHAR}, #{userLevel,jdbcType=SMALLINT}, ",
        "#{email,jdbcType=VARCHAR}, #{mobileNo,jdbcType=VARCHAR}, ",
        "#{emailStatus,jdbcType=SMALLINT}, #{mobileNoStatus,jdbcType=SMALLINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{platformId,jdbcType=VARCHAR})"
    })
    int insert(SmsUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @InsertProvider(type=SmsUserinfoSqlProvider.class, method="insertSelective")
    int insertSelective(SmsUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsUserinfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="smsUserId", property="smsUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userId", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="idCard", property="idCard", jdbcType=JdbcType.VARCHAR),
        @Result(column="userLevel", property="userLevel", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobileNo", property="mobileNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailStatus", property="emailStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="mobileNoStatus", property="mobileNoStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="platformId", property="platformId", jdbcType=JdbcType.VARCHAR)
    })
    List<SmsUserinfo> selectByExample(SmsUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Select({
        "select",
        "id, smsUserId, userId, userName, idCard, userLevel, email, mobileNo, emailStatus, ",
        "mobileNoStatus, createTime, platformId",
        "from sms_userinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="smsUserId", property="smsUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userId", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="idCard", property="idCard", jdbcType=JdbcType.VARCHAR),
        @Result(column="userLevel", property="userLevel", jdbcType=JdbcType.SMALLINT),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobileNo", property="mobileNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="emailStatus", property="emailStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="mobileNoStatus", property="mobileNoStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="platformId", property="platformId", jdbcType=JdbcType.VARCHAR)
    })
    SmsUserinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SmsUserinfo record, @Param("example") SmsUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SmsUserinfo record, @Param("example") SmsUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SmsUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Update({
        "update sms_userinfo",
        "set smsUserId = #{smsUserId,jdbcType=VARCHAR},",
          "userId = #{userId,jdbcType=VARCHAR},",
          "userName = #{userName,jdbcType=VARCHAR},",
          "idCard = #{idCard,jdbcType=VARCHAR},",
          "userLevel = #{userLevel,jdbcType=SMALLINT},",
          "email = #{email,jdbcType=VARCHAR},",
          "mobileNo = #{mobileNo,jdbcType=VARCHAR},",
          "emailStatus = #{emailStatus,jdbcType=SMALLINT},",
          "mobileNoStatus = #{mobileNoStatus,jdbcType=SMALLINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "platformId = #{platformId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SmsUserinfo record);

    @Select(" select count(*) from sms_userinfo ")
    int selectCountByAll();

    @Select({
            " select",
            " id, smsUserId, userId, userName, idCard, userLevel, email, mobileNo, emailStatus, ",
            " mobileNoStatus, createTime, platformId",
            " from sms_userinfo su",
            " order by su.createTime desc ",
            " limit #{offset},#{pagesize} "
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="smsUserId", property="smsUserId", jdbcType=JdbcType.VARCHAR),
            @Result(column="userId", property="userId", jdbcType=JdbcType.VARCHAR),
            @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
            @Result(column="idCard", property="idCard", jdbcType=JdbcType.VARCHAR),
            @Result(column="userLevel", property="userLevel", jdbcType=JdbcType.SMALLINT),
            @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
            @Result(column="mobileNo", property="mobileNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="emailStatus", property="emailStatus", jdbcType=JdbcType.SMALLINT),
            @Result(column="mobileNoStatus", property="mobileNoStatus", jdbcType=JdbcType.SMALLINT),
            @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="platformId", property="platformId", jdbcType=JdbcType.VARCHAR)
    })
    List<SmsUserinfo> selectListByPaging(@Param("offset") int offset, @Param("pagesize")  int pageSize);
}