package com.lcyj.sms.dao.mapper;

import com.lcyj.sms.model.SmsUserinfoWhitelists;
import com.lcyj.sms.model.SmsUserinfoWhitelistsExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SmsUserinfoWhitelistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="countByExample")
    int countByExample(SmsUserinfoWhitelistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @DeleteProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="deleteByExample")
    int deleteByExample(SmsUserinfoWhitelistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Delete({
        "delete from sms_userinfo_whitelists",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Insert({
        "insert into sms_userinfo_whitelists (id, smsUserId, ",
        "userName, startDateTime, ",
        "endDateTime, limitType, ",
        "createTime, description, ",
        "plantformId, serverId)",
        "values (#{id,jdbcType=INTEGER}, #{smsUserId,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{startDateTime,jdbcType=TIMESTAMP}, ",
        "#{endDateTime,jdbcType=TIMESTAMP}, #{limitType,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR}, ",
        "#{plantformId,jdbcType=VARCHAR}, #{serverId,jdbcType=VARCHAR})"
    })
    int insert(SmsUserinfoWhitelists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @InsertProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="insertSelective")
    int insertSelective(SmsUserinfoWhitelists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @SelectProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="smsUserId", property="smsUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="startDateTime", property="startDateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endDateTime", property="endDateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="limitType", property="limitType", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="plantformId", property="plantformId", jdbcType=JdbcType.VARCHAR),
        @Result(column="serverId", property="serverId", jdbcType=JdbcType.VARCHAR)
    })
    List<SmsUserinfoWhitelists> selectByExample(SmsUserinfoWhitelistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Select({
        "select",
        "id, smsUserId, userName, startDateTime, endDateTime, limitType, createTime, ",
        "description, plantformId, serverId",
        "from sms_userinfo_whitelists",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="smsUserId", property="smsUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="startDateTime", property="startDateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endDateTime", property="endDateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="limitType", property="limitType", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="plantformId", property="plantformId", jdbcType=JdbcType.VARCHAR),
        @Result(column="serverId", property="serverId", jdbcType=JdbcType.VARCHAR)
    })
    SmsUserinfoWhitelists selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SmsUserinfoWhitelists record, @Param("example") SmsUserinfoWhitelistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SmsUserinfoWhitelists record, @Param("example") SmsUserinfoWhitelistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @UpdateProvider(type=SmsUserinfoWhitelistsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SmsUserinfoWhitelists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo_whitelists
     *
     * @mbggenerated Sat Feb 29 10:46:03 CST 2020
     */
    @Update({
        "update sms_userinfo_whitelists",
        "set smsUserId = #{smsUserId,jdbcType=VARCHAR},",
          "userName = #{userName,jdbcType=VARCHAR},",
          "startDateTime = #{startDateTime,jdbcType=TIMESTAMP},",
          "endDateTime = #{endDateTime,jdbcType=TIMESTAMP},",
          "limitType = #{limitType,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "description = #{description,jdbcType=VARCHAR},",
          "plantformId = #{plantformId,jdbcType=VARCHAR},",
          "serverId = #{serverId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SmsUserinfoWhitelists record);
}